[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "relife"
version = "2.0.0"
requires-python = ">=3.11"
dependencies = [
    "numpy", # 1.26.4
    "scipy",
    "matplotlib",
    "typing-extensions",
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["relife*"]  # ["*"] by default

[project.optional-dependencies]
dev = [
    "pytest",
    "pandas",

    "nox",
    "isort",
    "black",
    "pylint",
    "mypy",
    "no-implicit-optional",

    "sphinx",
    "pydata-sphinx-theme",
    "sphinx-copybutton",
    "sphinx-design",
    "numpydoc",
    "nbsphinx",
    "myst-parser",
    "jupyterlab",
]

[tool.isort]
profile = 'black'

[tool.pylint.format]
max-line-length = "88"
max-args = 10
disable = """
    line-too-long,
"""
ignored-modules = "scipy.special"

# mypy does not recognize Tuple[Any, ...] notation (bug)
# see : https://github.com/python/mypy/issues/9459
[[tool.mypy.overrides]]
module = ["relife2.types"]
disable_error_code = ["misc"]

# current scipy is untyped and does not work with mypy
# see : https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
[[tool.mypy.overrides]]
module = ["scipy.*"]
ignore_missing_imports = true
