[build-system] # see setuptools quickstart
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "relife"
version = "2.0.0"
requires-python = ">=3.11"
dependencies = [
    "numpy", # 1.26.4
    "scipy",
    "matplotlib",
    "typing-extensions",
]

[tool.setuptools.packages.find] # project structure is "flat layout"
where = ["."] # current directory for flat layout
include = ["relife*"]  # ["*"] by default

[project.optional-dependencies]
dev = [
    "pytest",
    "pandas",

    "nox",
    "isort",
    "black",
    "pylint",
    "mypy",
    "no-implicit-optional",
    "scipy-stubs", # needed to type hint scipy https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-library-stubs-or-py-typed-marker

    "sphinx",
    "pydata-sphinx-theme",
    "sphinx-copybutton",
    "sphinx-design",
    "numpydoc",
    "nbsphinx",
    "myst-parser",
    "jupyterlab",
]

[tool.black]
line-length = 120

[tool.isort]
profile = 'black'

[tool.mypy]
plugins = "numpy.typing.mypy_plugin" # needed to type hing nympy

[[tool.mypy.overrides]]
module = [
    "relife/data/*",
    "relife/likelihood/*",
    "relife/policy/*",
    "relife/stochastic_process/*",
]
ignore_errors = true


[tool.pylint.format]
max-line-length = "88"
max-args = 10
disable = """
    line-too-long,
"""
ignored-modules = "scipy.special"


# pytest
[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-rxXs"
# addopts = "-rxXs -k 'not test_ls_integrate[loglogistic]'"
testpaths = [
    "test/test_lifetime_model/test_distribution.py",
    "test/test_parametric_model.py",
    "test/test_quadrature.py"
]
