name: Build and deploy Github pages
on: [push]
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '3.1.11'

      - name : Install Python dependencies
        run: | # dev version with sphinx 
          pip install ".[dev]" 

      - name: Build Sphinx Doc
        run: |
          sphinx-build -M html ./doc/source ./doc/build -Ea

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # branch on which files are commited
          folder: ./doc/build/html # The folder the action should deploy.
